language: bash
os: windows

install:
 - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

env:
 - COMPILER=MSVC_PROJ PLATFORM=x64 CONFIG=Debug
 - COMPILER=MSVC_PROJ PLATFORM=x64 CONFIG=Release
 - COMPILER=MSVC_PROJ PLATFORM=Win32 CONFIG=Debug
 - COMPILER=MSVC_PROJ PLATFORM=Win32 CONFIG=Release
 - COMPILER=MSVC_NMAKE PLATFORM=x64 CONFIG=Debug
 - COMPILER=MSVC_NMAKE PLATFORM=x64 CONFIG=Release
 - COMPILER=MSVC_NMAKE PLATFORM=Win32 CONFIG=Debug
 - COMPILER=MSVC_NMAKE PLATFORM=Win32 CONFIG=Release
 - COMPILER=CLANG_NMAKE PLATFORM=x64 CONFIG=Debug
 - COMPILER=CLANG_NMAKE PLATFORM=x64 CONFIG=Release
 - COMPILER=GCC_MAKE PLATFORM=x64 CONFIG=Debug
 - COMPILER=GCC_MAKE PLATFORM=x64 CONFIG=Release
 - COMPILER=CLANG_MAKE PLATFORM=x64 CONFIG=Debug
 - COMPILER=CLANG_MAKE PLATFORM=x64 CONFIG=Release

script:
 - ./_build/ci/travis/build.cmd

branches:
  only:
  - master
